/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author JoséRobertoFernandes
 */
public class ScreenHome extends javax.swing.JPanel {
        private Card totalCard;
        private Card catsCard;
        private Card dogsCard;

        private javax.swing.JLayeredPane cardgrid;
        private javax.swing.JLabel tableDescriptionLabel;
        private javax.swing.JScrollPane jScrollPane1;
        private PanelBorder panelBorder;
        private Table table;

        /**
         * Creates new form ScreenHome
         */
        public ScreenHome() {
                initComponents();

                totalCard.setData(getTotalCard());
                catsCard.setData(getCatsCard());
                dogsCard.setData(getDogsCard());

                // TABELA
                jScrollPane1.getViewport().setBackground(Color.white);
                JPanel p = new JPanel();
                p.setBackground(Color.white);
                jScrollPane1.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);

                // ID NOME TELEFONE VALOR SERVICO STATUS
                table.addRow(new Object[] { "1", "Jose", "19912345678", "90", "Banho", StatusType.PENDENTE });
                table.addRow(new Object[] { "1", "Jose", "19912345678", "120", "Tosa", StatusType.CONCLUIDO });
                table.addRow(new Object[] { "1", "Jose", "19912345678", "90", "Banho", StatusType.PENDENTE });

                /*
                 * table.addRow(new Object[]{"1", "Jose", "19912345678","120", "Tosa",
                 * StatusType.CONCLUIDO});
                 * table.addRow(new Object[]{"1", "Jose", "19912345678","90", "Banho",
                 * StatusType.PENDENTE});;
                 */

        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */

        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {
                cardgrid = new javax.swing.JLayeredPane();
                totalCard = new Card();
                catsCard = new Card();
                dogsCard = new Card();
                panelBorder = new PanelBorder();
                tableDescriptionLabel = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                table = new Table();

                setBackground(new java.awt.Color(255, 255, 255));
                setPreferredSize(new java.awt.Dimension(1016, 531));

                cardgrid.setLayout(new java.awt.GridLayout(1, 0, 10, 0));
                cardgrid.add(totalCard);
                cardgrid.add(catsCard);
                cardgrid.add(dogsCard);

                panelBorder.setForeground(new java.awt.Color(255, 255, 255));

                tableDescriptionLabel.setText("Agendamentos");

                jScrollPane1.setBorder(null);

                table.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {

                                },
                                new String[] {
                                                "ID", "Nome", "Telefone", "Valor", "Serviço", "Status"
                                }) {
                        boolean[] canEdit = new boolean[] {
                                        false, false, false, false, false, false
                        };

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit[columnIndex];
                        }
                });
                jScrollPane1.setViewportView(table);

                javax.swing.GroupLayout panelBorderLayout = new javax.swing.GroupLayout(panelBorder);
                panelBorder.setLayout(panelBorderLayout);
                panelBorderLayout.setHorizontalGroup(
                                panelBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(panelBorderLayout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(panelBorderLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(tableDescriptionLabel)
                                                                                .addComponent(jScrollPane1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                974,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                panelBorderLayout.setVerticalGroup(
                                panelBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(panelBorderLayout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(tableDescriptionLabel)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jScrollPane1)
                                                                .addContainerGap()));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(15, 15, 15)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addComponent(panelBorder,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(cardgrid))
                                                                .addContainerGap(15, Short.MAX_VALUE)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(cardgrid,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(panelBorder,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)));
        }// </editor-fold>//GEN-END:initComponents

        private CardModel getTotalCard() {
                return new CardModel(
                                new ImageIcon(getClass().getResource("resources/ico/user.png")),
                                "Total",
                                "10",
                                "Lorem ipsum dolor sit amet");
        }

        private CardModel getCatsCard() {
                return new CardModel(new ImageIcon(getClass().getResource("resources/ico/profit.png")), "Gato",
                                "20",
                                "Lorem ipsum dolor sit amet");
        }

        private CardModel getDogsCard() {
                return new CardModel(new ImageIcon(getClass().getResource("resources/ico/flag.png")),
                                "Cachorro",
                                "30",
                                "Lorem ipsum dolor sit amet");
        }
}
