/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author JoséRobertoFernandes
 */
public class ScreenCad extends javax.swing.JPanel implements ActionListener {

        /**
         * Creates new form ScreenCad
         */
        public ScreenCad() {
                initComponents();
                jButton1.addActionListener(this);
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */

        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                inputnome = new javax.swing.JTextField();
                inputtel = new javax.swing.JTextField();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                inputservico = new javax.swing.JComboBox<>();
                inputvalor = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                jButton1 = new javax.swing.JButton();

                setBackground(new java.awt.Color(255, 255, 255));

                jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jLabel1.setText("Cadastro");

                inputnome.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                inputnomeActionPerformed(evt);
                        }
                });

                jLabel2.setText("Nome");

                jLabel3.setText("Telefone");

                jLabel4.setText("Serviço");

                inputservico.setModel(
                                new javax.swing.DefaultComboBoxModel<>(new String[] { "Banho", "Tosa", "Consulta" }));
                inputservico.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                inputservicoActionPerformed(evt);
                        }
                });

                inputvalor.setText("0");

                jLabel6.setText("Subtotal:");

                jButton1.setBackground(new java.awt.Color(231, 229, 229));
                jButton1.setText("Enviar");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(26, 26, 26)
                                                                                                .addComponent(jLabel1,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                192,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(82, 82, 82)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                .addComponent(jButton1)
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                false)
                                                                                                                                                .addComponent(inputnome)
                                                                                                                                                .addComponent(jLabel2)
                                                                                                                                                .addComponent(jLabel4)
                                                                                                                                                .addComponent(inputservico,
                                                                                                                                                                0,
                                                                                                                                                                218,
                                                                                                                                                                Short.MAX_VALUE))
                                                                                                                                .addGap(50, 50, 50)
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                false)
                                                                                                                                                .addComponent(inputtel,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                218,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(jLabel3)
                                                                                                                                                .addGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                                                layout.createSequentialGroup()
                                                                                                                                                                                .addComponent(jLabel6)
                                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                                                .addComponent(inputvalor,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                119,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                                                                .addContainerGap(448, Short.MAX_VALUE)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(22, 22, 22)
                                                                .addComponent(jLabel1)
                                                                .addGap(26, 26, 26)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel2)
                                                                                .addComponent(jLabel3))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(inputnome,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                40,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(inputtel,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                40,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(54, 54, 54)
                                                                .addComponent(jLabel4)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addComponent(inputvalor,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addGroup(layout.createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                .addComponent(inputservico,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                40,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(jLabel6)))
                                                                .addGap(85, 85, 85)
                                                                .addComponent(jButton1)
                                                                .addContainerGap(123, Short.MAX_VALUE)));
        }// </editor-fold>//GEN-END:initComponents

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed

        }// GEN-LAST:event_jButton1ActionPerformed

        private void inputservicoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_inputservicoActionPerformed
        }// GEN-LAST:event_inputservicoActionPerformed

        private void inputnomeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_inputnomeActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_inputnomeActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JTextField inputnome;
        private javax.swing.JComboBox<String> inputservico;
        private javax.swing.JTextField inputtel;
        private javax.swing.JLabel inputvalor;
        private javax.swing.JButton jButton1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel6;
        // End of variables declaration//GEN-END:variables

        @Override
        public void actionPerformed(ActionEvent e) {
                // System.out.println("the button is pressed");
                String Snome = inputnome.getText();
                String Stel = inputtel.getText();
                String Sservico = (String) inputservico.getSelectedItem();
                if (Sservico.equals("Banho")) {
                        inputvalor.setText("80");
                }
                if (Sservico.equals("Tosa")) {
                        inputvalor.setText("160");
                }
                if (Sservico.equals("Consulta")) {
                        inputvalor.setText("320");
                }
                String Svalor = inputvalor.getText();
                DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
                LocalDateTime now = LocalDateTime.now();
                System.out.println(Snome + Stel + Sservico + Svalor + dtf.format(now));

                // ENVIA POST JSON

                // Do something with http.getInputStream()
                // throw new UnsupportedOperationException("Not supported yet."); // Generated
                // from
                // nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }
}
